cmake_minimum_required(VERSION 3.10)

message(STATUS "Host system: ${CMAKE_HOST_SYSTEM_NAME}")

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)

if (ARCH)
  include(${CMAKE_CURRENT_LIST_DIR}/arch/${ARCH}.cmake)
endif ()
